name: A workflow for team 4
on:
  push:
    branches:
      - master
jobs:
  CityUnitTests:
    name: City Unit Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: City Unit Tests
        run: mvn -Dtest=com.napier.team4.CityReporterUnitTest test
      - name: CodeCov
        uses: codecov/codecov-action@v2
        with:
          directory: ./target/site/jacoco
          flags: City-Unit-Tests
          verbose: true
  CountryUnitTests:
    name: Country Unit Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Country Unit Tests
        run: mvn -Dtest=com.napier.team4.CountryReporterUnitTest test
      - name: CodeCov
        uses: codecov/codecov-action@v2
        with:
          directory: ./target/site/jacoco
          flags: Country-Unit-Tests
          verbose: true
  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Integration Tests and CodeCov
        run: |
          docker build -t database ./db 
          docker run --name world -dp 33062:3306 database
          mvn -Dtest=com.napier.team4.AppIntegrationTest test          
          docker stop world
          docker rm world
          docker image rm database
      - name: CodeCov
        uses: codecov/codecov-action@v2
        with:
          directory: ./target/site/jacoco
          flags: IntegrationTests
          verbose: true
          branch: master
  build:
    name: Build Run in Docker and Deploy Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests
          docker-compose up --abort-on-container-exit
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            ./target/*.jar